services:
  - name: static-site
    type: static
    buildCommand: echo 'Build successful'
    publishPath: public
    envVars:
      - key: NODE_ENV
        value: production

routes:
  - type: rewrite
    source: /*
    destination: /index.html
